# Generated by Django 4.2.5 on 2023-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=200)),
                ('bn', models.CharField(max_length=200)),
                ('wu', models.CharField(max_length=200)),
                ('jt', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('howhelp', models.CharField(max_length=200)),
            ],
        ),
    ]
