# Generated by Django 4.2.5 on 2023-09-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('business', models.TextField()),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
