# Generated by Django 4.2.5 on 2023-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_service_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='years',
            field=models.IntegerField(max_length=100),
        ),
    ]
